# Generated by Django 4.1.7 on 2023-03-09 16:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_participants', models.PositiveIntegerField()),
                ('total_prizes', models.PositiveIntegerField()),
                ('ko_stages', models.BooleanField(default=False)),
                ('edition', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FootballClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('establishment_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1850), django.core.validators.MaxValueValidator(2023)])),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(default='', max_length=50)),
                ('budget', models.PositiveIntegerField()),
                ('home_kit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FootballPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('nationality', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('position', models.CharField(default='', max_length=20)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.footballclub')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
