# Generated by Django 4.1.7 on 2023-03-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trophies_won', models.PositiveIntegerField(default=0)),
                ('no_of_participations', models.PositiveIntegerField(default=1)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.footballclub')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.competition')),
            ],
        ),
    ]
