# Generated by Django 4.1.7 on 2023-03-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='clubs',
            field=models.ManyToManyField(through='players.Record', to='players.footballclub'),
        ),
        migrations.AddField(
            model_name='footballclub',
            name='competitions',
            field=models.ManyToManyField(through='players.Record', to='players.competition'),
        ),
    ]
